### ISSUE TITLE
Renaming OSX Helper app

### ISSUE THREAD

**Issue by kierans** [evshiron/nwjs-builder-phoenix#108]
As per the [Package and Distribute](http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/#mac-os-x) docs for Mac, the `nwjs Helper` app should be renamed.

The name for the Helper should probably match the `product_string` in the [manifest](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#product_string) to be consistent with what NW.js is looking for.

**Comment by kierans** [comment]
Interestingly if you **don't** rename the Helper app with NW.js v0.24.4 (and one assumes later) and you have a `product_string` in your manifest, when the app starts it looks for `$product_string Helper.app` and doesn't start correctly because it can't find the Helper (`ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.`)

**Comment by sadikyalcin** [comment]
Is this possible at the moment? I'm on OSX and I can nwjs Helper on activity monitor.

**Comment by kierans** [comment]
@sadikyalcin You should put a thumbs-up/comment on #109.
