### ISSUE TITLE
Icons for NSIS Installer and Uninstaller

### ISSUE THREAD

**Issue by evshiron** [evshiron/nwjs-builder-phoenix#18]

**Comment by fritx** [comment]
The windows exe icon is of low resolution.
I used to use resource-hacker, and the provided ico was fine.

**Comment by evshiron** [comment]
I was experienced this with `rcedit` too, which was the reason why I used Resource Hacker in `nwjs-builder`, which will scale the original icon if some sizes are missing.

The icons for installer and uninstaller are handled by NSIS itself automatically, without `rcedit` involved. So I would recommend using [iConvertIcons](https://iconverticons.com/online/) to produce an `.ico` with frames of different resolutions and see if it works. If it doesn't, please tell me and I will search about it.
