### ISSUE TITLE
There are several problems

### ISSUE THREAD

**Issue by phpjishu** [evshiron/nwjs-builder-phoenix#20]
1、Can you pack the MAC installation package on windows?
2、`packed` parameter configuration error!
3、`nsis` parameter configuration error!

**Comment by evshiron** [comment]
Detailed information?

What's that "MAC installation package" means? `.pkg`? `.dmg`? The current `.zip` and `.7z` should be OK for simple app distribution.
If error happened, can you please put some logs so I can know what was happening?
