### ISSUE TITLE
NSIS Custom String Internationalization

### ISSUE THREAD

**Issue by evshiron** [evshiron/nwjs-builder-phoenix#22]
See [LangString](http://nsis.sourceforge.net/Reference/LangString).

**Comment by fritx** [comment]
Hi @evshiron , how could I use this feature, since there is no nsi thing exposed to me in the demo app.

**Comment by evshiron** [comment]
Sorry it's not implemented at the moment and I am still considering what this should look like.

The idea came to me when I wrote some English strings in the generated scripts, which looked quite uncomfortable when used in installers of other languages.
The original idea is to add some `LangString` for some languages for these strings, but it has low priority until someone requests for it.

As it isn't implemented yet, I want to know why you want this feature and what's your expectation for it, so I can start with an overall idea. Thanks.

**Comment by evshiron** [comment]
https://github.com/evshiron/nwjs-builder-phoenix/tree/nsis-i18n

I made a prototype here, hopefully you can clone and `npm install`, try it out and see if it helps in your cases. If you have other ideas please share with me :)
