### ISSUE TITLE
Starting with 0.22.0 package for macOS is more than double the size

### ISSUE THREAD

**Issue by arudnev** [evshiron/nwjs-builder-phoenix#30]
It seems that in 0.22 NW.js changed what is included in the download for macOS, switching to symbolic links for some of the nested folders.

Before 0.22 this is what you normally would have in the nwjs package (actual folders with content).
<img width="312" alt="screenshot 2017-04-24 12 46 12" src="https://cloud.githubusercontent.com/assets/1192686/25348614/c6411c88-28ec-11e7-9d02-591ab1d77597.png">

In 0.22 instead of some of the folders that it used to have now it has symbolic links.
<img width="314" alt="screenshot 2017-04-24 12 45 29" src="https://cloud.githubusercontent.com/assets/1192686/25348763/523f4b7e-28ed-11e7-8953-4ae5ef3c22e1.png">

In the package for the app we end up having triple of original content.
<img width="317" alt="screenshot 2017-04-24 12 44 38" src="https://cloud.githubusercontent.com/assets/1192686/25348863/a25f5504-28ed-11e7-93b9-1f0eb83834fd.png">

One copy ends up in "nwjs Framework.framework", and two more copies in "nwjs Framework.framework/Versions/Current" and "nwjs Framework.framework/Versions/A" (the original content for this distro).

**Comment by evshiron** [comment]
`nwjs-builder-phoenix` started to dereference symlinks when I started using `lerna`, which automatically creates symlinks between packages, and the test for building wouldn't work without doing it.

I don't like symlinks at all and avoid using it especially in distribution, so I post an issue on nwjs/nw.js#5873 and wait for the answer.

If it's expected for later versions of NW.js, I am going copy NW.js while keeping the symlinks unchanged, and then copy project files with dereferenced symlinks. But these symlinks should fail someone who want to build macOS apps from Windows.

**Comment by evshiron** [comment]
If you are interested, commenting out [this line](https://github.com/evshiron/nwjs-builder-phoenix/blob/master/src/lib/Builder.ts#L475) should work (try finding the corresponding line in `./node_modules/nwjs-builder-phoenix/dist/lib/Builder.js`).

**Comment by arudnev** [comment]
When I discovered the issue last week I added extra step in our build process to remove content of "${name}.app/Contents/Versions/${version}/nwjs Framework.framework/Versions" after nwjs-builder-phoenix is done and before we run appdmg to create images, that way we don't have any symlinks or duplicates in our distro. 
I think I'll wait for response to the ticket about intent of that change in NW.js distro and if that's here to stay then I'll test how it works without dereferencing. Or maybe some logic can be added to skip "**/nwjs Framework.framework/Versions" as part of the mentioned copy operation.

**Comment by evshiron** [comment]
According to @rogerwang, it's an intended change. I am preparing for an update for this.

**Comment by evshiron** [comment]
Hopefully this will be fixed in `nwjs-builder-phoenix` 1.10.2, please report back when you have time. I am having a slow Internet connection at the moment and can't test for it completely.

**Comment by arudnev** [comment]
Thank you, seems to be all fine now. I was trying to test it yesterday, but was hitting issues with signature verification after install of the package downloaded from internet, wanted to make sure that signing issues were not related to use of symlinks.
