### ISSUE TITLE
Packed:true Build Fails for windows on Windows

### ISSUE THREAD

**Issue by tsnelson1** [evshiron/nwjs-builder-phoenix#35]
When I set the option 'packed' to true, I cannot get the build to work. The compress functionality appears to add '.zip' to the temporary filename during build, and when it tries to find it to copy the package, it no longer can be found. This appears to be an issue with the '7zip-bin' package. Each time I see a filename with the name given in the not found filename with '.zip' extension appended to the filename in the Temp folder.

`Starting building tasks... { tasks: [ [ 'win', 'x86' ], [ 'win', 'x64' ] ],
  concurrent: false }
Building for win, x86 starts...
Fetching NW.js binary... { platform: 'win', arch: 'x86', version: '0.22.1', flavor: 'sdk' }
Building targets...
Building directory target starts...
{ Error: ENOENT: no such file or directory, open 'C:\Users\xxx\AppData\Local\Temp\tmp-26568vQHtcVPlm7C4'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\tmp-26568vQHtcVPlm7C4' }

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "distwin"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! QuestarStudent@3.4.83 distwin: `build --win --x86 --x64 --mirror https://dl.nwjs.io/ .`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the QuestarStudent@3.4.83 distwin script 'build --win --x86 --x64 --mirror https://dl.nwjs.io/ .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the QuestarStudent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build --win --x86 --x64 --mirror https://dl.nwjs.io/ .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs QuestarStudent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls QuestarStudent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\git\sec_nwjs\npm-debug.log
`

**Comment by evshiron** [comment]
It's because `util.tmpName()` returns a path without extension, and when the path is passed to `7zip-bin`,  it automatically appends one if there isn't an extension.
I fix this but `Builder.buildNsis7zTarget()` won't complete after creating a `.7z` archive. Will investigate later.

**Comment by evshiron** [comment]
Should be fixed in `nwjs-builder-phoenix` 1.11.1.
