### ISSUE TITLE
Using packed: true doesn't unpack and run properly

### ISSUE THREAD

**Issue by tsnelson1** [evshiron/nwjs-builder-phoenix#37]
Running the EXE on Windows extracts the packed exe, but doesn't seem to know where it was extracted to when launching, and expects it to have been extracted to its local folder, which it shouldn't be.

I only know this as after I built, after running and encountering a stalled launch, I killed the process and copied my extracted source to the local folder and once I reran it, it launched.

**Comment by evshiron** [comment]
If it's expecting launching from the local directory, the generated `package.json` stripped by `nwjs-builder-phoenix` might be the case, but I can't reproduce with the sample project and the LTS version.

Would you mind removing the `package.json` in the built directory and see if it launches? If not, could you please provide a reproducing sample which I can investigate with?

Thanks.

**Comment by tsnelson1** [comment]
You were right, this was a mistake in forgetting to include my dependencies in my package.json! In converting my application over to nwjs-build-phoenix from nw-builder, I had moved all my dependencies of my app to devDependencies, but a couple were needed for the app, rather than just the build process.

Thanks so much for all your enhancements and fixes thus far, it is greatly appreciated!
