### ISSUE TITLE
Option to change default directory structure

### ISSUE THREAD

**Issue by TatriX** [evshiron/nwjs-builder-phoenix#38]
As I can see there the path to a output directory is hardcoded like this:
```js
 const targetDir = resolve(this.dir, config.output, `${ pkg.name }-${ pkg.version }-${ platform }-${ arch }`);
```
Because I moved from `nw-builder` I have a lot of scripts which works on it's directory structure i.e.
```
${root}/${appname}/${platform+arch}/
```
which is a good for further scripting because it's not tied to a version. Sure I can make links or update my scripts to handle this, but it would be helpfull if I could just replace `nw-builder` without this troubles.

Thank you for your work.

**Comment by evshiron** [comment]
Greetings and nice point.

One question, will symbols like `rootDir`, `outputDir`, `name`, `version`, `platform` and `arch` be enough for you? Others will be added if there is a request for them.

**Comment by evshiron** [comment]
I want to reuse the `build.output` property and if no symbol is presented, old behavior will be used.

For example, if `./dist/` is set, the `output` property will be set to `./dist/${NAME}-${VERSION}-${PLATFORM}-${ARCH}` internally, and the `targetDir` will be `resolve(this.dir, this.parseOutput(output))`.

I don't know if there is a need for specifying different paths for different targets, which should take a bit more time to implement.

**Comment by TatriX** [comment]
I think it should work.

**Comment by evshiron** [comment]
This feature should have been added in `nwjs-builder-phoenix` 1.13.0.

Considering the `build.output` is used in some other aspects, I am not extending the `build.output`, but add a new `build.outputPattern`, where we can use `${NAME}`, `${VERSION}`, `${PLATFORM}` and `${ARCH}` to specify the base name. The completed path altering should be able to achieve by modifying both `build.output` and `build.outputPattern`.

**Comment by TatriX** [comment]
Awesome, thank you!
