### ISSUE TITLE
Linux+packed don't work

### ISSUE THREAD

**Issue by TatriX** [evshiron/nwjs-builder-phoenix#39]
Running the following (when `packed:  true`)
```sh
./node_modules/.bin/build --linux --x64 .
```
leads to a 
```sh
Starting building tasks... { tasks: [ [ 'linux', 'x64' ] ], concurrent: false }
Building for linux, x64 starts...
Fetching NW.js binary... { platform: 'linux',
  arch: 'x64',
  version: 'stable',
  flavor: 'sdk' }
Building targets...
Building directory target starts...
{ Error: EACCES: permission denied, open '$PATH/build/rogalia-0.35.0-linux-x64/nw'
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '$PATH/build/rogalia-0.35.0-linux-x64/nw' }
```

**Comment by evshiron** [comment]
I don't know if `$PATH` can be used. I currently don't have a Linux machine to reproduce this, but I think the permission of the executable should be correct and building for Linux on macOS doesn't have this issue.

Could you change `$PATH` to another path and see if it works?

**Comment by TatriX** [comment]
I just changed actual path to a variable. In the real output there is a full path to a file.

**Comment by evshiron** [comment]
Ouch, then I have misunderstood. I installed Fedora 25 in VirtualBox just now and `npm test ./test/Builder.js` passed, which means the building should complete without the error described above.

As I can't reproduce it on my machine, would you mind running `npm test ./test/Builder.js` on yours and see if it works? See [README](https://github.com/evshiron/nwjs-builder-phoenix) for completed steps of setting up an environment for development. Thanks.

BTW modify the mirror in `./test/Builder.js` if needed.

**Comment by TatriX** [comment]
Hm, I have no idea why, but now it works.

**Comment by TatriX** [comment]
One more question: is it possible to `chmod +x` the binary for linux?

**Comment by evshiron** [comment]
https://github.com/evshiron/nwjs-builder-phoenix/blob/master/assets/project/package.json#L15

`packed` should have been set for the sample project. Hmm, so why? What was the permission of that `nw` file?

Yes, the `chmod +x` should be done for you. I will fix it some time later.

**Comment by TatriX** [comment]
Well there is no `nw` file in the resultion directory...

**Comment by evshiron** [comment]
:(

**Comment by TatriX** [comment]
Oh, I think I found another bug. I had no space in my `/tmp` dir and due to this packed executable was empty file.
