### ISSUE TITLE
How to build Mac x64 and both x86 and x64 linux?

### ISSUE THREAD

**Issue by tsnelson1** [evshiron/nwjs-builder-phoenix#40]
Thanks for all your help in the past. I would like to try to build three packages in one command, how do I get to build just one Mac OSX version (as x86 is no longer available) and both x86 and x64 versions of Linux? Is there a chance to support ignoring a 404 failure for a missing NWJS package if others exist and complete the other builds?

Currently I get a failure to build any of the above or I need to build Mac in a separate command from Linux if I want all three builds.

**Comment by evshiron** [comment]
Building modern versions of NW.js for macOS x86 should now be ignored in `nwjs-builder-phoenix` 1.12.1.
