### ISSUE TITLE
Mac packed file missing package.json and doesn't run properly

### ISSUE THREAD

**Issue by tsnelson1** [evshiron/nwjs-builder-phoenix#41]
I have noticed that when I build the Mac with the 'Packed' flag (I have other concurrent builds that need packed:true), I would like them all to run, but after building, the Mac version doesn't run properly. When I checked the difference in file structure, the Mac is missing the stripped package.json file.

In the packed vs unpacked code for mac is nearly identical except for one line in the unpacked code:
`
await this.writeStrippedManifest(resolve(appRoot, 'package.json'), pkg, config);
`

With this code missing, it just launches an unconfigured version of NWJS.

**Comment by evshiron** [comment]
Should be fixed in `nwjs-builder-phoenix` 1.12.1.
