### ISSUE TITLE
Build multiple arch/platforms at once?

### ISSUE THREAD

**Issue by TatriX** [evshiron/nwjs-builder-phoenix#44]
nw-builder has an option
```js
platforms: ["win32", "linux64", "linux32", "osx64"],
```
so I can run it once and build all required targets.
How can I achieve this?

**Comment by evshiron** [comment]
Try `build --concurrent`.

**Comment by TatriX** [comment]
So if I don't want to build 2 unnecessary targets I should run build 4 times in my case?

**Comment by TatriX** [comment]
If I could do something like `--win32 --linux64 --linux32 --osx64` I would be happy.

**Comment by evshiron** [comment]
Added in `nwjs-builder-phoenix` 1.14.0. e.g. `build --tasks win-x86,win-x64,mac-x64 .`.

**Comment by TatriX** [comment]
Cool! Thank you!
