### ISSUE TITLE
Enable GCM Flag isn't passed to nwjs when installing/running chrome app

### ISSUE THREAD

**Issue by robotsrule** [evshiron/nwjs-builder-phoenix#47]
In order for the chrome.gcm API to work with nwjs when running a chrome app, the --enable-gcm flag needs to be passed as a command line argument to the nwjs executable.  Is there any way to configure the installer to pass this command line argument to nwjs when a user runs the installed executable?  It would be ideal if it only passed the flag if the chrome app manifest.json file included the GCM permission, but at this point I'd settle for an option I can set manually during the build of the installer.  I know I can have users create a shortcut that has the command line argument, but that is not an ideal situation.  Any thoughts on how to achieve this?

**Comment by evshiron** [comment]
Currently custom shortcut isn't supported, which will require either a new option or the ability to custom NSIS scripts. I don't want to add an option for this specified task, and the support for custom NSIS scripts requires some work to accomplish, which might be too complex for this.

A possible way to achieve this is to check `--enable-gcm` at startup, and if it's not set, the app spawns itself with `--enable-gcm` option appended and closes itself. I don't know if this (using node.js `child_process` module to spawn in a Chrome App) will work but if you are interested, read the [docs](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/) about `single-instance` for caveats.

If the above won't work for you, you can custom NSIS scripts at the moment by using `nwjs-builder-phoenix/nsis-gen` to generate scripts and build specified scripts. Read [/test/nsis-gen.js](https://github.com/evshiron/nwjs-builder-phoenix/blob/master/test/nsis-gen.js) for reference.

**Comment by robotsrule** [comment]
Thank you for the leads on possible solutions and for your work on this project!  I will report back if I have any success with either approach.

**Comment by robotsrule** [comment]
After a lot of messing around with different options, I ended up utilizing child_process.spawn to fire up an external batch file (on windows) that kills the existing process and runs it with the correct flag.  Using shell:true, detached:true, stdio:'ignore', and setting cwd to the appropriate path on the spawn options were all necessary for this to work properly, but it does end up working.

I was able to detect the presence of the --enable-gcm argument by looking at the contents of nw.App.argv

Thanks again for the suggestion.

**Comment by robotsrule** [comment]
So it turns out this self-destructing app that restarts itself is completely unnecessary.

Apparently you can add the "chromium-args" property in the chrome app manifest.json (I thought it could only be used with package.json on a vanilla nwjs app).  So adding:

"chromium-args": "--enable-gcm" 

to the manifest.json will run it with the feature turned on and none of the nonsense involved with passing it to the main nw executable.

**Comment by evshiron** [comment]
I thought `chromium-args` was for Chromium's rather than arguments added by NW.js when I saw the documentation, as a result I didn't mention it in the last time.

Anyway, looks like it's solved now and thanks for sharing with me :)
