### ISSUE TITLE
Offline Use?

### ISSUE THREAD

**Issue by gardiner** [evshiron/nwjs-builder-phoenix#50]
Hi, thanks for the great work so far!

I want to create different packages for different targets while being offline and was wondering if and how I could use nwjs-builder-phoenix in that scenario.
If all else fails I might set up a local mirror, but I don't know which files I need and where to put them (obviously, I don't want to clone a complete mirror site, only the required versions/targets).

Thanks for your support!
Ole.

**Comment by evshiron** [comment]
You can download binaries from the mirror and save it with original filenames in `./node_modules/nwjs-builder-phoenix/caches/`. As long as you don't specify a symbol for version like `legacy` or `stable`, an Internet connection shouldn't be a must have.

I didn't test it yet, but if anything doesn't work as above please report back and I will fix.

**Comment by gardiner** [comment]
Thanks, that seems to work! :)

Best,
Ole.
