### ISSUE TITLE
running installer on sample project on windows leads to broken shortcuts 

### ISSUE THREAD

**Issue by codekiln** [evshiron/nwjs-builder-phoenix#52]
After modifying the build script in the [package.json](https://github.com/evshiron/nwjs-builder-phoenix/blob/master/assets/project/package.json) at [nwjs-builder-phoenix/assets/project/](https://github.com/evshiron/nwjs-builder-phoenix/tree/master/assets/project) so it works for windows in x86, running on Windows 7 points to "C:\Program Files\nwjs-builder-phoenix\Project\Project.exe", but that directory is not created during installation. Instead, it's in C:\Users\IEUser\AppData\Local\project.

Also, is there a way to modify the generated NSIS installer to be able to provide execution arguments to the executable?

**Comment by evshiron** [comment]
Greetings. I just tried building the sample project and the shortcut created should be consistent with the installation directory. Could you provide a sample of your `package.json` so I can investigate with?

**Comment by evshiron** [comment]
Currently there isn't a way to specify command line arguments for created shortcuts. I can start working on it if there is a need.

**Comment by evshiron** [comment]
Hmmm, I wonder if we allow specifying command line arguments for shortcuts, what will happen if the user double click on the executable?

**Comment by codekiln** [comment]
Hi @evshiron - with regards to the installer on the sample app, I got it to work by removing the `build.nsis.installDirectory` key from line [40 of the package.json](https://github.com/evshiron/nwjs-builder-phoenix/blob/master/assets/project/package.json#L40), which caused it to [return to the default](https://github.com/evshiron/nwjs-builder-phoenix/blob/master/docs/Options.md#buildnsis---nsisconfig) of `$LOCALAPPDATA\\${_APPNAME}`. This produced an NSIS installer that worked all around pretty well.

With respect to command line shortcuts, I don't know if there's anything we can do about the executable itself, but having shortcuts in Program Files and the Desktop which passed the correct args would go a long way, at least towards my current use case (relevant context: https://github.com/nwjs/nw.js/issues/5846, https://groups.google.com/forum/#!topic/nwjs-general/MkNh7mdimfA)

**Comment by evshiron** [comment]
What about nwjs/nw.js#5957 and evshiron/nwjs-builder-phoenix#47?

**Comment by codekiln** [comment]
@evshiron thank you for these tips! I will fill in here when I know more, but so far, I have determined that if I put 
`"chromium-args": "--enable-logging=stderr --load-extension='./ppbllmlcmhfnfflbkbinnhacecaankdh'"`
in the manifest.json, then run build, the resulting executable has the extension loaded according to the chrome console: 

```
> nw.global.chrome.management.get('ppbllmlcmhfnfflbkbinnhacecaankdh', function(data){console.log(JSON.stringify(data, null, 2))})
undefined
VM631:1 {
  "description": "Enables Cisco Jabber phone calls and video calls",
  "enabled": true,
  "homepageUrl": "",
  "hostPermissions": [],
  "icons": [
    {
      "size": 16,
      "url": "chrome://extension-icon/ppbllmlcmhfnfflbkbinnhacecaankdh/16/0"
    },
    {
      "size": 48,
      "url": "chrome://extension-icon/ppbllmlcmhfnfflbkbinnhacecaankdh/48/0"
    },
    {
      "size": 128,
      "url": "chrome://extension-icon/ppbllmlcmhfnfflbkbinnhacecaankdh/128/0"
    }
  ],
  "id": "ppbllmlcmhfnfflbkbinnhacecaankdh",
  "installType": "development",
  "isApp": false,
  "mayDisable": true,
  "name": "Cisco Web Communicator",
  "offlineEnabled": false,
  "optionsUrl": "",
  "permissions": [
    "management",
    "nativeMessaging"
  ],
  "shortName": "Cisco Web Communicator",
  "type": "extension",
  "updateUrl": "http://127.0.0.1/",
  "version": "3.1.0.363"
}
```

**Comment by codekiln** [comment]
I can confirm that I don't need to be able to pass arguments to the executable if I only need to do things that are valid Chromium command line arguments. Thank you for your assistance!
