### ISSUE TITLE
--remote-debugging-port and other nw options

### ISSUE THREAD

**Issue by gius80** [evshiron/nwjs-builder-phoenix#53]
Hi, I'm trying to figure out how to use some nw.js options with nwjs.builder (such as --remote-debugging-port or --load-extension).

I'm using this syntax:

run --remote-debugging-port=9999 -r .
 
but it seems that options are totally ignored. Is there a way to use nw options with nwjs-builder-phoenix?

Thanks!
Igor

**Comment by evshiron** [comment]
Try `run -- . --remote-debugging-port=9999 -r`, the `--` is the convention to stop argument parsing and I think `yargs` (the module used to parse arguments in `nwjs-builder-phoenix`) should work with it.

If this doesn't work please report back and I will fix it :)

**Comment by gius80** [comment]
Awesome, it works!
Thanks a lot!
