### ISSUE TITLE
Is building for Mac supported? 

### ISSUE THREAD

**Issue by codekiln** [evshiron/nwjs-builder-phoenix#54]
The README says: 

* Building for Windows, macOS and Linux
  * Common: `zip`, `7z`
  * Windows: `nsis`, [`nsis7z`](./docs/FAQs.md)
  * **macOS: TODO**
  * Linux: TODO

I've seen several issues that look as though mac is currently supported at least in a nascent form. I already have nw-builder working for mac builds for my app, and would just like to know if it is currently supported to determine if I want to port the mac app build process from nw-builder to nw-builder-phoenix.

**Comment by evshiron** [comment]
This is the supported target list, for example `dmg` will replace this `TODO` once implemented. You can build targets like `.zip` and `.7z` for macOS at the moment. See [Options](https://github.com/evshiron/nwjs-builder-phoenix/blob/master/docs/Options.md) for supported options for macOS.

**Comment by codekiln** [comment]
FWIW, I've had great luck with using [appdmg](https://github.com/LinusU/node-appdmg) for nw.js apps; it could probably be incorporated pretty easily given the right pass through options.

**Comment by evshiron** [comment]
LinusU/node-appdmg looks cool, will try it when I have the motivation. PRs are welcomed :)

**Comment by codekiln** [comment]
@evshiron so does building `mac` type with no target currently output a ready `.app` folder?

**Comment by evshiron** [comment]
Yes, it should be a `.app` folder inside a folder specified by the `output` and `outputPattern` options.
