### ISSUE TITLE
Remove cmd.exe DOS window from nsis installer?

### ISSUE THREAD

**Issue by codekiln** [evshiron/nwjs-builder-phoenix#55]
When using nsis7z target, the resulting installer has a "Run Now" button at the end. When using that feature, it spawns a cmd.exe window. *When running the application later through Program Files or the shortcut on the desktop, this superfluous window is absent*. Is there a way to configure the NSIS installer so that it does not show this cmd.exe window when run upon closing the installer? 

Alternatively, is there a way to disable that checkbox, so that it does not have the "run now" feature?

The alternative window is messing up my application, which needs to find the first window in order to position a video overlay.

**Comment by evshiron** [comment]
Related: https://github.com/evshiron/nwjs-builder-phoenix/blob/master/src/lib/nsis-gen/NsisComposer.ts#L183

I think changing it from `"$INSTDIR\\\${_APPNAME}.exe"` to `"start $INSTDIR\\\${_APPNAME}.exe"` or alternatives should do the trick.

I am busy recently and if you are interested you can modify the source code and use `nwjs-builder-phoenix/dist/lib/nsis-gen` to generate and build modified NSIS scripts (See evshiron/nwjs-builder-phoenix#7 for some information).

Also if you want to hide the `Run Project` option, simply comment out that line should work.

**Comment by codekiln** [comment]
Hi @evshiron - thank you for the info. I will update here when I learn more.

**Comment by codekiln** [comment]
@evshiron is there an easy way I could do this locally without submitting a PR?

**Comment by evshiron** [comment]
@codekiln I think it should work by modifying `/node_modules/nwjs-builder-phoenix/dist/lib/nsis-gen/NsisComposer.js` as said above.

**Comment by codekiln** [comment]
I will try that out. Thank you!

**Comment by codekiln** [comment]
I just wanted to comment back here that I haven't yet had the time to try out the modification, but it's still an important issue to my users. I haven't forgotten about the issue and will update here when I know more. 

Are there any other users who do *not* experience an extra DOS command window when usine nw-builder-phoenix on Windows?
