### ISSUE TITLE
How to set build flavor during dist build? [Question] 

### ISSUE THREAD

**Issue by Ajeey** [evshiron/nwjs-builder-phoenix#58]
This is the dist command - 
`"dist": "build --tasks win-x86,win-x64,linux-x86,linux-x64,mac-x64 --mirror https://dl.nwjs.io/ .",`

By default the `flavor: 'normal'`.

How do I set to pick up sdk flavor?

**Comment by evshiron** [comment]
Try setting `package.json:build.nwFlavor` to `sdk`.

**Comment by Ajeey** [comment]
Awesome that works and thank you for the super fast reply :)

**Comment by evshiron** [comment]
:)

**Comment by Ajeey** [comment]
For anybody else looking for the same question, this is what you need to do - 

```
"build": {
		"nwVersion": "0.22.3",
		"nwFlavor": "sdk"
	},
```
