### ISSUE TITLE
[Question] Is nw-autoupdater supported?

### ISSUE THREAD

**Issue by Ajeey** [evshiron/nwjs-builder-phoenix#60]
It is mentioned that to use **nw-autoupdater** (https://github.com/dsheiko/nw-autoupdater), we need to package the app by using - https://github.com/evshiron/nwjs-builder. But since this repo (nwjs-builder) recommends your repo(nwjs-builder-phoenix), I am curious as to does **nwjs-builder-phoenix** support nw-autoupdater?

**Comment by evshiron** [comment]
I didn't try it but I think it's supported as the outcome is of the same structure.

**Comment by Ajeey** [comment]
Okay I will give it a try.

**Comment by Ajeey** [comment]
Seems like it does not work - https://github.com/dsheiko/nw-autoupdater/issues/21
