### ISSUE TITLE
Unable to set icon

### ISSUE THREAD

**Issue by RichardFoss** [evshiron/nwjs-builder-phoenix#61]
I have a project that I am currently running on Windows from the command line using nw.js (nw .).
I want to create an installation file and decided to make use of nwjs-builder-phoenix. Thanks for the capability!
I have followed the instructions to create a package.json. When I perform "npm run dist", I get the following error:

Error: rcedit.exe failed with exit code 1. Fatal error: Unable to set icon
    at ChildProcess.<anonymous> (D:\AVBFlexSDKDistr\node_modules\rcedit\lib\rcedit.js:60:16)

I decided to try using the icon files in the example, pd.icns, but get the same error.

Given below is my package.json. Any help would be much appreciated! Should "npm run dist" create installation packages?

{
  "name": "AVBFlex",
  "version": "1.0.0",
  "description": "AVBFlex",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
	"dist": "build --tasks win-x86,win-x64 --mirror https://dl.nwjs.io/ .",
        "start": "run --x86 --mirror https://dl.nwjs.io/ ."
  },
  "author": "Richard Foss",
  "license": "ISC",
  "build": {
	"nwVersion": "0.23.5",
	"packed": true,
	"targets": [
		"nsis"
	],
	"win": {
		"productName": "AVBFlex",
		"companyName": "ImmersiveDSP",
		"icon": "./assets/pd.icns"
	},
	"nsis": {
		"installDirectory": "$PROGRAMFILES\\${_ImmersiveDSP}\\${_AVBFlex}"
	}
  }, 
  "devDependencies": {
		"nwjs-builder-phoenix": "^1.14.3"
  },
  "window": {
	"icon": "./assets/pd.png"
  }
}

**Comment by evshiron** [comment]
For Windows you need an `.ico` file, the `.icns` file is used on macOS.

**Comment by RichardFoss** [comment]
Oh no, sorry, that was careless of me! Thanks for the quick response.
