### ISSUE TITLE
Does it support 32-bit windows systems?

### ISSUE THREAD

**Issue by boneVidy** [evshiron/nwjs-builder-phoenix#67]
Does it support 32-bit windows systems?

**Comment by evshiron** [comment]
Well. You can edit the previous post instead of closing it.

Yes.

**Comment by boneVidy** [comment]
`"scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "build": "build --tasks win-x64,win-x32,mac-x64，win-win32 --mirror https://npm.taobao.org/mirrors/nwjs/ .",
        "build:win32": "build --win --win32 --mirror https://npm.taobao.org/mirrors/nwjs/ .",
        "build:osx64": "build --mac --x64 --mirror https://npm.taobao.org/mirrors/nwjs/ .",
        "build:win64": "build --win --x64 --mirror https://npm.taobao.org/mirrors/nwjs/ ."
    },`
My configuration is like this, but when I execute the `npm run build` command, I did not see the windows32 folder in the  './dist'

**Comment by evshiron** [comment]
Replace `--win32` to `--x86`. Also you are using a non-ASCII comma in the task list.

**Comment by boneVidy** [comment]
thx!
