### ISSUE TITLE
Unclear on how to specify your own ffmpeg

### ISSUE THREAD

**Issue by mscreenie** [evshiron/nwjs-builder-phoenix#69]
I've built my own ffmpeg with lots of additions and want to specify it in the build. I can't see anywhere where I can do this? 

Alternatively can I specify my own nwjs lts zip ? I could just replace the ffmpeg that is shipped by default with mine.

**Comment by evshiron** [comment]
You should be able to do this by replacing the `.zip` for a specified version in `/node_modules/nwjs-builder-phoenix/caches/`.
