### ISSUE TITLE
nw version 0.14.6 Can not start on windows Xp system 

### ISSUE THREAD

**Issue by boneVidy** [evshiron/nwjs-builder-phoenix#70]
my pkg.json is like this
` 
    "build:win32": "build --win --x86 --mirror https://npm.taobao.org/mirrors/nwjs/ ./src",
    
  },`

![img_8493](https://user-images.githubusercontent.com/10415170/29023288-a7655404-7b9f-11e7-9874-47b10fb072d2.JPG)

**Comment by evshiron** [comment]
Try using older versions of NW.js.

**Comment by boneVidy** [comment]
@evshiron my nwjs‘s version is 0.14.6

**Comment by evshiron** [comment]
@boneVidy Could you try versions from 0.13.x to 0.14.7 and see if any of them works?

**Comment by boneVidy** [comment]
@evshiron The cause of this bug is that I replaced ffmepg. DLL.
Thank you for answering me
