### ISSUE TITLE
Do not pull nwjs binary every time.

### ISSUE THREAD

**Issue by chtseac** [evshiron/nwjs-builder-phoenix#73]
I'm using nwjs at work to make a small tool for doing stuff with routers. I would need to disconnect my computer every time I want to test, but this tool wants connection whenever I would start the application.

Can you add a flag to make it not pull the newest binary every time? Like a `--no-fetch` flag?

```
chtseac $ npm start

> projectname@1.0.0 start /home/chtseac/Projects/projectname
> run --x64 --mirror https://dl.nwjs.io/ .

Fetching NW.js binary... { platform: 'linux',
  arch: 'x64',
  version: '0.24.3',
  flavor: 'sdk' }
{ [Error: getaddrinfo EAI_AGAIN dl.nwjs.io:443]
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'dl.nwjs.io',
  host: 'dl.nwjs.io',
  port: 443 }

...

npm ERR! projectname@1.0.0 start: `run --x64 --mirror https://dl.nwjs.io/ .`
npm ERR! Exit status 255
```

**Comment by evshiron** [comment]
Could you try the latest `nwjs-builder-phoenix` 1.14.4 and see if it works? I can only get `ENOTFOUND` on macOS which is already tolerated.

**Comment by chtseac** [comment]
Sorry, I should have updated before opening an issue! I was on 1.14.3 before.

```
Fetching NW.js binary... { platform: 'linux',
  arch: 'x64',
  version: '0.24.3',
  flavor: 'sdk' }
DNS lookup timeout, use local caches at this time.
Launching NW.js app...
NW.js app exited with 0.
```
