### ISSUE TITLE
Support --mirror to pick binary from local disk

### ISSUE THREAD

**Issue by Ajeey** [evshiron/nwjs-builder-phoenix#75]
It'd be great to have a flag which says pick the binary from the user's system.
Something like 
`--mirror /Desktop/nw-binary/nw`

**Comment by evshiron** [comment]
Would you might using `http-server` module or something like that to serve these files and specifying the local HTTP server as the mirror? This would require no change to `nwjs-builder-phoenix` but should work in your case.

Underneath `nwjs-builder-phoenix` uses `request` module to create HTTP connections and I don't know if accessing local files are allowed.
