### ISSUE TITLE
Failed to load libGLESv2.so

### ISSUE THREAD

**Issue by cryomi** [evshiron/nwjs-builder-phoenix#79]
Hi, I've upgraded NWJS Version from 0.24.4 (works fine) to 0.25 SDK, made a build for linux (ubuntu 16),on macos using https://github.com/evshiron/nwjs-builder-phoenix. win, macos builds - work fine.

while starting app on linux I see blank screen, running app from terminal leads to error output in cycle.

```
[3594:3594:0907/105316.147021:ERROR:gl_implementation.cc(245)] Failed to load /linux-x64/swiftshader/libGLESv2.so: /linux-x64/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[3594:3594:0907/105316.152250:ERROR:gpu_child_thread.cc(252)] Exiting GPU process due to errors during initialization
```

Downloaded directly https://dl.nwjs.io/v0.25.0/nwjs-sdk-v0.25.0-linux-x64.tar.gz - starts and is operational, including dev-tools

**Comment by cryomi** [comment]
Posted the same at https://github.com/nwjs/nw.js/issues/6142
I am not sure where from this bug is originating.

**Comment by evshiron** [comment]
Could you tell if the `libGLESv2.so` file is present in the built app directory, along with the executable?

**Comment by evshiron** [comment]
Well, I tried it and it seems that the file isn't shipped within the binary archive. I don't have a Linux currently and I think it should be an issue with NW.js itself.

**Comment by cryomi** [comment]
I checked my linux build w/ nwjs 0.24.4, it also has no libGLESv2.so.

**Comment by cryomi** [comment]
I did clean install of Ubuntu17, result is the same - error. NWJS team answered to check with 'nwjs-builder-phoenix' team, because nwjs 0.25 starts on ubunto without issues (the same for me).

**Comment by cryomi** [comment]
I found similar bug reports, most of them are connected to Chromium/Linux combination - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864606, reported on Sun, 11 Jun 2017
