### ISSUE TITLE
is node-main support ?

### ISSUE THREAD

**Issue by cobola** [evshiron/nwjs-builder-phoenix#97]
i add node-main in the package.json
```
"node-main": "./app.js",
```

the app.js startup express  server 

but it not works 

how to debug that ? no error logs

**Comment by TheJaredWilcurt** [comment]
I just tested this and it works fine. As long as the file is included in the `files` array, either explicitly or in a glob pattern like `**/*` and it is not in the `excludes`, it will be copied to your dist. Also you need to make sure you are not using `strippedProperties` to remove `node-main`.

You should inspect your `node_modules` in your dist folder to see if it includes all the dependencies you need. If `express` is a `devDependencies`, then it will be stripped and not installed in your dist.

**Comment by cobola** [comment]
many thanks ,i use electron instead ,i will try later .

**Comment by tadada** [comment]
> I just tested this and it works fine. As long as the file is included in the `files` array, either explicitly or in a glob pattern like `**/*` and it is not in the `excludes`, it will be copied to your dist. Also you need to make sure you are not using `strippedProperties` to remove `node-main`.
> 
> You should inspect your `node_modules` in your dist folder to see if it includes all the dependencies you need. If `express` is a `devDependencies`, then it will be stripped and not installed in your dist.

There is no node_module in dist directory

**Comment by TheJaredWilcurt** [comment]
`node_modules` folder should only exist if you have items in your package.json under `dependencies`
